### ISSUE TITLE
"Artefacts: All data and tool support for replication are available at https://github.com/SerVal-DTF/APR-Efficiency.git"

### ISSUE THREAD

**Issue by jose** [SerVal-DTF/APR-Efficiency#1]
Hi,

The paper [On the Efficiency of Test Suite based Program Repair A Systematic Assessment of 16 Automated Repair Systems for Java Programs](https://dl.acm.org/doi/abs/10.1145/3377811.3380338) at some point mentions that:
> **Artefacts:** All data and tool support for replication are available at https://github.com/SerVal-DTF/APR-Efficiency.git

However, in this repository, I've only managed to find the patches generated by each APR tool.  Are you planning to release the "tool support" bit?

--
Best,
Jose

**Comment by Kui-Liu** [comment]
ACS and SimFix are available at: https://drive.google.com/drive/folders/1OS9-GG2WQjFpvOPARaLW-k9b-9ZpO_3J?usp=sharing

**Comment by jose** [comment]
Thanks.  Any chance you could summarize the changes you made to ACS and SimFix and why you made them?  I'm wondering why there was the need to create a "MySimFix" version of the "SimFix" tool...  Are those change any relevant to be reported (merged?) into the master branch of each tool?

**Comment by Kui-Liu** [comment]
The changes of ACS and SimFix are made on their fault localization part, because their original versions have different fault localization settings,
Such changes are not reported into their master branches.

**Comment by jose** [comment]
> The changes of ACS and SimFix are made on their fault localization part, because their original versions have different fault localization settings. 

Ok, could you please summarize those changes and why were they made?

> Such changes are not reported into their master branches.

Any particular reason to not merge that?

**Comment by Kui-Liu** [comment]
We made such changes because we want to remove the impact from different fault localization settings.
The changes are just replacing their original fault localization settings with the same way of reading the fault localization results from the same fault localization setting.

Such changes are made to investigate their bug-fixing performance with the same fault localization setting, which is different from their studies. I am not sure whether they will accept such pull requests or not, that is why I didn't make such pull requests for merging.

**Comment by jose** [comment]
Ok, thanks.
